// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB864yQZBF_5MTE7jjBrTWft1mCqM1-dOA',
    appId: '1:321498173059:web:96a2166070e8987e1c95b6',
    messagingSenderId: '321498173059',
    projectId: 'event-planning-4a133',
    authDomain: 'event-planning-4a133.firebaseapp.com',
    storageBucket: 'event-planning-4a133.firebasestorage.app',
    measurementId: 'G-9EL4477JT3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkTARQTJL5kf2e9QAq4cU9D1RyLxAToUA',
    appId: '1:321498173059:android:6e49e5923eb4f72f1c95b6',
    messagingSenderId: '321498173059',
    projectId: 'event-planning-4a133',
    storageBucket: 'event-planning-4a133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApgJnI6HWIA_NYSPBtjlgMTzipkNbmysc',
    appId: '1:321498173059:ios:5ca254810527a6c41c95b6',
    messagingSenderId: '321498173059',
    projectId: 'event-planning-4a133',
    storageBucket: 'event-planning-4a133.firebasestorage.app',
    iosBundleId: 'com.example.eventlyProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApgJnI6HWIA_NYSPBtjlgMTzipkNbmysc',
    appId: '1:321498173059:ios:5ca254810527a6c41c95b6',
    messagingSenderId: '321498173059',
    projectId: 'event-planning-4a133',
    storageBucket: 'event-planning-4a133.firebasestorage.app',
    iosBundleId: 'com.example.eventlyProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB864yQZBF_5MTE7jjBrTWft1mCqM1-dOA',
    appId: '1:321498173059:web:a0335e684fbd3f371c95b6',
    messagingSenderId: '321498173059',
    projectId: 'event-planning-4a133',
    authDomain: 'event-planning-4a133.firebaseapp.com',
    storageBucket: 'event-planning-4a133.firebasestorage.app',
    measurementId: 'G-6BJ1G4FDRS',
  );
}
